-- populate the category table
insert into category (id, name) values (1, 'Baschetball');
insert into category (id, name) values (3, 'Swimming');
insert into category (id, name) values (4, 'Tennis');
insert into category (id, name) values (5, 'Football');
insert into category (id, name) values (6, 'Ping-Pong');
insert into category (id, name) values (7, 'Jogging');
insert into category (id, name) values (8, 'Golf');
insert into category (id, name) values (9, 'Skiing');
insert into category (id, name) values (10, 'Snowboarding');
insert into category (id, name) values (11, 'Surf');
insert into category (id, name) values (12, 'Gym Session');
insert into category (id, name) values (13, 'American Football');
insert into category (id, name) values (14, 'Bowling');
insert into category (id, name) values (15, 'Boxing');
insert into category (id, name) values (16, 'Chess');
insert into category (id, name) values (17, 'Hiking');
insert into category (id, name) values (18, 'Criket');
insert into category (id, name) values (19, 'Fencing');
insert into category (id, name) values (20, 'Hockey');
insert into category (id, name) values (21, 'Sailing');
insert into category (id, name) values (22, 'Yoga');
insert into category (id, name) values (23, 'Card Games');
insert into category (id, name) values (24, 'Pool');
insert into category (id, name) values (25, 'Voleyball');
